spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:mysql://localhost:3306/libraryapi
    username: root
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true